{{eval_name}}:
  id: {{eval_name}}.{{evaluation_id}}.{{version}}
  metrics: [accuracy]

{{eval_name}}.{{evaluation_id}}.{{version}}:
  class: {{class_name}}
  args:
    samples_jsonl: {{jsonl_file_path}}
    fuzzy: {{fuzzy}}
    extract_gql: {{extract_gql}}

